"""
S&P 500 ticker list — verified as of March 2026.

Yahoo Finance format notes:
  - Class-share tickers use a dash, not a dot: BRK-B (not BRK.B), BF-B (not BF.B)
  - Marsh & McLennan changed from MMC → MRSH on January 14, 2026
  - WBA (Walgreens) delisted August 28, 2025 (acquired by Sycamore Partners); replaced by IBKR
  - SNDK is SanDisk Corporation (spun off from WDC in 2024)
  - Q is Qnity Electronics (DuPont spinoff, 2024)
  - XYZ is Block, Inc. (formerly traded as SQ)
  - PSKY is Paramount Skydance Corporation (rebranded from PARA after Skydance merger)
  - SOLV is Solventum Corporation (3M healthcare spinoff)
  - GEV is GE Vernova (spun off from GE in 2024)
  - GEHC is GE HealthCare Technologies (spun off from GE in 2023)
"""

SP500_TICKERS: list[str] = [
    # Information Technology
    "NVDA", "AAPL", "MSFT", "AVGO", "AMD", "QCOM", "TXN", "ADBE", "CRM", "INTU",
    "CSCO", "ACN", "IBM", "AMAT", "LRCX", "MU", "KLAC", "SNPS", "CDNS", "ADI",
    "MCHP", "PANW", "FTNT", "NOW", "ORCL", "INTC", "HPE", "HPQ", "DELL", "WDC",
    "STX", "NTAP", "KEYS", "FFIV", "AKAM", "FSLR", "APP", "SNDK",
    "ANET", "NXPI", "CRWD", "ADSK", "DDOG", "FTNT",
    # Communication Services
    "GOOGL", "GOOG", "META", "NFLX", "CMCSA", "VZ", "T", "DIS", "CHTR", "TMUS",
    "EA", "TTWO", "MTCH", "WBD", "FOXA", "FOX", "OMC", "LYV", "PSKY",
    "NWSA", "NWS",
    # Consumer Discretionary
    "AMZN", "TSLA", "HD", "MCD", "LOW", "TJX", "NKE", "SBUX", "BKNG", "MAR",
    "HLT", "RCL", "CCL", "NCLH", "LVS", "MGM", "WYNN", "F", "GM", "BBY",
    "TGT", "ROST", "DG", "DLTR", "YUM", "CMG", "DRI", "EBAY", "AZO", "ORLY",
    "GPC", "PHM", "DHI", "LEN", "NVR", "HAS", "TPR", "RL", "DASH",
    "DECK", "GDDY", "CVNA", "XYZ", "ULTA",
    "ABNB", "UBER", "WDAY", "TTD", "TSCO",
    # Consumer Staples
    "WMT", "PG", "KO", "PEP", "PM", "MO", "MDLZ", "CL", "KMB",
    "GIS", "CPB", "HRL", "SJM", "CAG", "MKC", "CHD", "CLX", "EL",
    "HSY", "MNST", "KDP", "STZ", "BF-B", "TAP", "SYY", "CVS", "KVUE",
    "KR", "COST",
    # Health Care
    "UNH", "JNJ", "LLY", "ABBV", "MRK", "TMO", "ABT", "DHR", "BMY", "AMGN",
    "GILD", "VRTX", "ISRG", "REGN", "BIIB", "IQV", "ZTS", "IDXX",
    "SYK", "BSX", "EW", "BDX", "MTD", "A", "HOLX", "ALGN", "DXCM", "PODD",
    "HCA", "UHS", "CNC", "HUM", "CI", "ELV", "MOH", "MCK", "COR", "CAH",
    "PFE", "HSIC", "WAT", "SOLV", "RVTY", "TECH", "CRL", "ZBH", "RMD",
    "GEHC", "INCY", "BAX", "DVA", "LH", "DGX", "STE", "WST", "TDY",
    "MRNA", "POOL",
    # Financials
    "BRK-B", "JPM", "BAC", "WFC", "GS", "MS", "C", "BLK", "SPGI", "MCO",
    "CB", "AXP", "V", "MA", "PYPL", "ICE", "CME", "NDAQ", "CBOE",
    "AON", "MRSH", "AJG", "WTW", "MET", "PRU", "AFL", "AIG", "HIG", "TRV",
    "PGR", "ALL", "L", "ERIE", "USB", "PNC", "TFC", "KEY",
    "RF", "FITB", "HBAN", "CFG", "MTB", "SCHW", "RJF",
    "TROW", "STT", "BK", "NTRS", "FIS", "FISV", "GPN",
    "COF", "SYF", "BX", "KKR", "APO", "ARES", "BEN", "IVZ",
    "AMP", "PFG", "ACGL", "EG", "WRB", "CINF", "AIZ",
    "COIN", "HOOD", "IBKR",
    # Industrials
    "HON", "UNP", "RTX", "CAT", "DE", "ETN", "NOC", "GD", "LMT", "LHX", "TDG",
    "WM", "RSG", "CTAS", "ROP", "GWW", "FAST", "AME", "VRSK", "EFX",
    "MSCI", "IT", "BR", "PAYC", "ITW", "PH", "ROK",
    "SWK", "XYL", "IR", "CARR", "OTIS", "TT", "JCI", "JBHT", "CHRW", "EXPD",
    "FDX", "UPS", "ODFL", "CSX", "NSC", "WAB",
    "DAL", "UAL", "LUV", "BA",
    "PLTR", "AXON", "LDOS",
    "GE", "GEV", "HWM", "TXT", "HII", "TKO",
    "PWR", "FIX", "EME", "BLDR", "URI", "TRMB",
    "NDSN", "DOV", "SNA", "JKHY", "J",
    "ADP", "CPRT", "GRMN", "PCAR", "CMI", "MMM",
    "EMR", "AOS", "ALLE", "EPAM", "GLW", "MSI",
    "APH", "CRH", "LULU", "TSN", "VRSN",
    # Energy
    "XOM", "CVX", "COP", "EOG", "SLB", "MPC", "PSX", "VLO", "HAL",
    "DVN", "APA", "BKR", "OKE", "KMI", "WMB", "EQT", "CTRA", "FANG",
    "OXY", "NRG", "CEG", "PCG", "EIX", "AES", "TRGP", "EXE",
    "VST",
    # Materials
    "LIN", "APD", "NUE", "FCX", "VMC", "MLM", "NEM", "BALL", "CF",
    "MOS", "CTVA", "DOW", "LYB", "PPG", "SHW", "ECL", "ALB",
    "IFF", "DD", "STLD", "BG", "SW", "IP", "PKG", "AMCR",
    # Real Estate
    "PLD", "AMT", "CCI", "EQIX", "PSA", "DLR", "O", "SPG", "WELL", "AVB",
    "EQR", "VTR", "ESS", "UDR", "CPT", "MAA", "REG", "KIM", "FRT",
    "BXP", "CBRE", "HST", "ARE", "VICI", "IRM", "EXR", "INVH",
    "DOC", "SBAC",
    # Utilities
    "NEE", "DUK", "SO", "D", "EXC", "SRE", "AEP", "XEL", "ED", "WEC",
    "DTE", "ES", "ETR", "FE", "NI", "CNP", "CMS",
    "LNT", "EVRG", "ATO", "PNW", "AWK",
    "PPL", "AEE",
    # Additional confirmed S&P 500 members
    "Q", "SMCI", "VTRS", "VLTO", "SWKS", "APTV", "ON", "FTV", "TYL",
    "TPL", "FDS", "FICO", "PEG", "PNR", "HUBB", "ROL", "ZBRA", "CTSH",
    "ADM", "AVY", "BRO", "CDW", "CIEN", "COO", "CSGP", "CPAY",
    "DPZ", "EXPE", "GEN", "GL", "GNRC", "IEX", "JBL",
    "KHC", "LII", "LW", "MAS", "MDT", "MPWR",
    "PAYX", "PTC", "TER", "TEL", "WY", "WSM",
]

# Deduplicate while preserving order
_seen: set[str] = set()
_deduped: list[str] = []
for _t in SP500_TICKERS:
    if _t not in _seen:
        _seen.add(_t)
        _deduped.append(_t)
SP500_TICKERS = _deduped

SP500_SECTORS: dict[str, str] = {
    # Information Technology
    **{t: "Information Technology" for t in [
        "NVDA", "AAPL", "MSFT", "AVGO", "AMD", "QCOM", "TXN", "ADBE", "CRM", "INTU",
        "CSCO", "ACN", "IBM", "AMAT", "LRCX", "MU", "KLAC", "SNPS", "CDNS", "ADI",
        "MCHP", "PANW", "FTNT", "NOW", "ORCL", "INTC", "HPE", "HPQ", "DELL", "WDC",
        "STX", "NTAP", "KEYS", "FFIV", "AKAM", "FSLR", "APP", "SNDK",
        "ANET", "NXPI", "CRWD", "ADSK", "DDOG",
        "Q", "SMCI", "SWKS", "ON", "TYL", "FICO", "ZBRA", "CTSH",
        "CDW", "CIEN", "GEN", "JBL", "MPWR", "PTC", "TER", "TEL",
        "FDS", "GLW", "MSI", "APH", "VRSN",
    ]},
    # Communication Services
    **{t: "Communication Services" for t in [
        "GOOGL", "GOOG", "META", "NFLX", "CMCSA", "VZ", "T", "DIS", "CHTR", "TMUS",
        "EA", "TTWO", "MTCH", "WBD", "FOXA", "FOX", "OMC", "LYV", "PSKY", "NWSA", "NWS",
    ]},
    # Consumer Discretionary
    **{t: "Consumer Discretionary" for t in [
        "AMZN", "TSLA", "HD", "MCD", "LOW", "TJX", "NKE", "SBUX", "BKNG", "MAR",
        "HLT", "RCL", "CCL", "NCLH", "LVS", "MGM", "WYNN", "F", "GM", "BBY",
        "TGT", "ROST", "DG", "DLTR", "YUM", "CMG", "DRI", "EBAY", "AZO", "ORLY",
        "GPC", "PHM", "DHI", "LEN", "NVR", "HAS", "TPR", "RL", "DASH",
        "DECK", "GDDY", "CVNA", "XYZ", "ULTA",
        "ABNB", "UBER", "WDAY", "TTD", "TSCO",
        "APTV", "DPZ", "EXPE", "WSM", "LULU",
    ]},
    # Consumer Staples
    **{t: "Consumer Staples" for t in [
        "WMT", "PG", "KO", "PEP", "PM", "MO", "MDLZ", "CL", "KMB",
        "GIS", "CPB", "HRL", "SJM", "CAG", "MKC", "CHD", "CLX", "EL",
        "HSY", "MNST", "KDP", "STZ", "BF-B", "TAP", "SYY", "CVS", "KVUE",
        "KR", "COST", "ADM", "KHC", "LW", "TSN",
    ]},
    # Health Care
    **{t: "Health Care" for t in [
        "UNH", "JNJ", "LLY", "ABBV", "MRK", "TMO", "ABT", "DHR", "BMY", "AMGN",
        "GILD", "VRTX", "ISRG", "REGN", "BIIB", "IQV", "ZTS", "IDXX",
        "SYK", "BSX", "EW", "BDX", "MTD", "A", "HOLX", "ALGN", "DXCM", "PODD",
        "HCA", "UHS", "CNC", "HUM", "CI", "ELV", "MOH", "MCK", "COR", "CAH",
        "PFE", "HSIC", "WAT", "SOLV", "RVTY", "TECH", "CRL", "ZBH", "RMD",
        "GEHC", "INCY", "BAX", "DVA", "LH", "DGX", "STE", "WST", "TDY",
        "MRNA", "POOL", "VTRS", "COO", "MDT",
    ]},
    # Financials
    **{t: "Financials" for t in [
        "BRK-B", "JPM", "BAC", "WFC", "GS", "MS", "C", "BLK", "SPGI", "MCO",
        "CB", "AXP", "V", "MA", "PYPL", "ICE", "CME", "NDAQ", "CBOE",
        "AON", "MRSH", "AJG", "WTW", "MET", "PRU", "AFL", "AIG", "HIG", "TRV",
        "PGR", "ALL", "L", "ERIE", "USB", "PNC", "TFC", "KEY",
        "RF", "FITB", "HBAN", "CFG", "MTB", "SCHW", "RJF",
        "TROW", "STT", "BK", "NTRS", "FIS", "FISV", "GPN",
        "COF", "SYF", "BX", "KKR", "APO", "ARES", "BEN", "IVZ",
        "AMP", "PFG", "ACGL", "EG", "WRB", "CINF", "AIZ",
        "COIN", "HOOD", "IBKR", "FDS", "BRO", "CPAY", "GL",
    ]},
    # Industrials
    **{t: "Industrials" for t in [
        "HON", "UNP", "RTX", "CAT", "DE", "ETN", "NOC", "GD", "LMT", "LHX", "TDG",
        "WM", "RSG", "CTAS", "ROP", "GWW", "FAST", "AME", "VRSK", "EFX",
        "MSCI", "IT", "BR", "PAYC", "ITW", "PH", "ROK",
        "SWK", "XYL", "IR", "CARR", "OTIS", "TT", "JCI", "JBHT", "CHRW", "EXPD",
        "FDX", "UPS", "ODFL", "CSX", "NSC", "WAB",
        "DAL", "UAL", "LUV", "BA",
        "PLTR", "AXON", "LDOS",
        "GE", "GEV", "HWM", "TXT", "HII", "TKO",
        "PWR", "FIX", "EME", "BLDR", "URI", "TRMB",
        "NDSN", "DOV", "SNA", "JKHY", "J",
        "ADP", "CPRT", "GRMN", "PCAR", "CMI", "MMM",
        "EMR", "AOS", "ALLE", "EPAM", "CRH",
        "VLTO", "FTV", "PNR", "HUBB", "ROL", "GNRC", "IEX", "LII", "MAS", "PAYX",
    ]},
    # Energy
    **{t: "Energy" for t in [
        "XOM", "CVX", "COP", "EOG", "SLB", "MPC", "PSX", "VLO", "HAL",
        "DVN", "APA", "BKR", "OKE", "KMI", "WMB", "EQT", "CTRA", "FANG",
        "OXY", "NRG", "CEG", "PCG", "EIX", "AES", "TRGP", "EXE", "VST",
        "TPL",
    ]},
    # Materials
    **{t: "Materials" for t in [
        "LIN", "APD", "NUE", "FCX", "VMC", "MLM", "NEM", "BALL", "CF",
        "MOS", "CTVA", "DOW", "LYB", "PPG", "SHW", "ECL", "ALB",
        "IFF", "DD", "STLD", "BG", "SW", "IP", "PKG", "AMCR", "AVY",
    ]},
    # Real Estate
    **{t: "Real Estate" for t in [
        "PLD", "AMT", "CCI", "EQIX", "PSA", "DLR", "O", "SPG", "WELL", "AVB",
        "EQR", "VTR", "ESS", "UDR", "CPT", "MAA", "REG", "KIM", "FRT",
        "BXP", "CBRE", "HST", "ARE", "VICI", "IRM", "EXR", "INVH",
        "DOC", "SBAC", "CSGP", "WY",
    ]},
    # Utilities
    **{t: "Utilities" for t in [
        "NEE", "DUK", "SO", "D", "EXC", "SRE", "AEP", "XEL", "ED", "WEC",
        "DTE", "ES", "ETR", "FE", "NI", "CNP", "CMS",
        "LNT", "EVRG", "ATO", "PNW", "AWK", "PPL", "AEE", "PEG",
    ]},
}

SP500_COMPANY_NAMES: dict[str, str] = {
    # Information Technology
    "NVDA": "NVIDIA Corporation",
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "AVGO": "Broadcom Inc.",
    "AMD": "Advanced Micro Devices Inc.",
    "QCOM": "QUALCOMM Incorporated",
    "TXN": "Texas Instruments Incorporated",
    "ADBE": "Adobe Inc.",
    "CRM": "Salesforce Inc.",
    "INTU": "Intuit Inc.",
    "CSCO": "Cisco Systems Inc.",
    "ACN": "Accenture plc",
    "IBM": "International Business Machines Corporation",
    "AMAT": "Applied Materials Inc.",
    "LRCX": "Lam Research Corporation",
    "MU": "Micron Technology Inc.",
    "KLAC": "KLA Corporation",
    "SNPS": "Synopsys Inc.",
    "CDNS": "Cadence Design Systems Inc.",
    "ADI": "Analog Devices Inc.",
    "MCHP": "Microchip Technology Incorporated",
    "PANW": "Palo Alto Networks Inc.",
    "FTNT": "Fortinet Inc.",
    "NOW": "ServiceNow Inc.",
    "ORCL": "Oracle Corporation",
    "INTC": "Intel Corporation",
    "HPE": "Hewlett Packard Enterprise Company",
    "HPQ": "HP Inc.",
    "DELL": "Dell Technologies Inc.",
    "WDC": "Western Digital Corporation",
    "STX": "Seagate Technology Holdings plc",
    "NTAP": "NetApp Inc.",
    "KEYS": "Keysight Technologies Inc.",
    "FFIV": "F5 Inc.",
    "AKAM": "Akamai Technologies Inc.",
    "FSLR": "First Solar Inc.",
    "APP": "AppLovin Corporation",
    "SNDK": "SanDisk Corporation",
    "ANET": "Arista Networks Inc.",
    "NXPI": "NXP Semiconductors N.V.",
    "CRWD": "CrowdStrike Holdings Inc.",
    "ADSK": "Autodesk Inc.",
    "DDOG": "Datadog Inc.",
    # Communication Services
    "GOOGL": "Alphabet Inc. (Class A)",
    "GOOG": "Alphabet Inc. (Class C)",
    "META": "Meta Platforms Inc.",
    "NFLX": "Netflix Inc.",
    "CMCSA": "Comcast Corporation",
    "VZ": "Verizon Communications Inc.",
    "T": "AT&T Inc.",
    "DIS": "The Walt Disney Company",
    "CHTR": "Charter Communications Inc.",
    "TMUS": "T-Mobile US Inc.",
    "EA": "Electronic Arts Inc.",
    "TTWO": "Take-Two Interactive Software Inc.",
    "MTCH": "Match Group Inc.",
    "WBD": "Warner Bros. Discovery Inc.",
    "FOXA": "Fox Corporation (Class A)",
    "FOX": "Fox Corporation (Class B)",
    "OMC": "Omnicom Group Inc.",
    "LYV": "Live Nation Entertainment Inc.",
    "PSKY": "Paramount Skydance Corporation",
    "NWSA": "News Corporation (Class A)",
    "NWS": "News Corporation (Class B)",
    # Consumer Discretionary
    "AMZN": "Amazon.com Inc.",
    "TSLA": "Tesla Inc.",
    "HD": "The Home Depot Inc.",
    "MCD": "McDonald's Corporation",
    "LOW": "Lowe's Companies Inc.",
    "TJX": "The TJX Companies Inc.",
    "NKE": "NIKE Inc.",
    "SBUX": "Starbucks Corporation",
    "BKNG": "Booking Holdings Inc.",
    "MAR": "Marriott International Inc.",
    "HLT": "Hilton Worldwide Holdings Inc.",
    "RCL": "Royal Caribbean Group",
    "CCL": "Carnival Corporation & plc",
    "NCLH": "Norwegian Cruise Line Holdings Ltd.",
    "LVS": "Las Vegas Sands Corp.",
    "MGM": "MGM Resorts International",
    "WYNN": "Wynn Resorts Limited",
    "F": "Ford Motor Company",
    "GM": "General Motors Company",
    "BBY": "Best Buy Co. Inc.",
    "TGT": "Target Corporation",
    "ROST": "Ross Stores Inc.",
    "DG": "Dollar General Corporation",
    "DLTR": "Dollar Tree Inc.",
    "YUM": "Yum! Brands Inc.",
    "CMG": "Chipotle Mexican Grill Inc.",
    "DRI": "Darden Restaurants Inc.",
    "EBAY": "eBay Inc.",
    "AZO": "AutoZone Inc.",
    "ORLY": "O'Reilly Automotive Inc.",
    "GPC": "Genuine Parts Company",
    "PHM": "PulteGroup Inc.",
    "DHI": "D.R. Horton Inc.",
    "LEN": "Lennar Corporation",
    "NVR": "NVR Inc.",
    "HAS": "Hasbro Inc.",
    "TPR": "Tapestry Inc.",
    "RL": "Ralph Lauren Corporation",
    "DASH": "DoorDash Inc.",
    "DECK": "Deckers Outdoor Corporation",
    "GDDY": "GoDaddy Inc.",
    "CVNA": "Carvana Co.",
    "XYZ": "Block Inc.",
    "ULTA": "Ulta Beauty Inc.",
    "ABNB": "Airbnb Inc.",
    "UBER": "Uber Technologies Inc.",
    "WDAY": "Workday Inc.",
    "TTD": "The Trade Desk Inc.",
    "TSCO": "Tractor Supply Company",
    # Consumer Staples
    "WMT": "Walmart Inc.",
    "PG": "The Procter & Gamble Company",
    "KO": "The Coca-Cola Company",
    "PEP": "PepsiCo Inc.",
    "PM": "Philip Morris International Inc.",
    "MO": "Altria Group Inc.",
    "MDLZ": "Mondelez International Inc.",
    "CL": "Colgate-Palmolive Company",
    "KMB": "Kimberly-Clark Corporation",
    "GIS": "General Mills Inc.",
    "CPB": "The Campbell's Company",
    "HRL": "Hormel Foods Corporation",
    "SJM": "The J.M. Smucker Company",
    "CAG": "Conagra Brands Inc.",
    "MKC": "McCormick & Company Incorporated",
    "CHD": "Church & Dwight Co. Inc.",
    "CLX": "The Clorox Company",
    "EL": "The Estee Lauder Companies Inc.",
    "HSY": "The Hershey Company",
    "MNST": "Monster Beverage Corporation",
    "KDP": "Keurig Dr Pepper Inc.",
    "STZ": "Constellation Brands Inc.",
    "BF-B": "Brown-Forman Corporation (Class B)",
    "TAP": "Molson Coors Beverage Company",
    "SYY": "Sysco Corporation",
    "CVS": "CVS Health Corporation",
    "KVUE": "Kenvue Inc.",
    "KR": "The Kroger Co.",
    "COST": "Costco Wholesale Corporation",
    # Health Care
    "UNH": "UnitedHealth Group Incorporated",
    "JNJ": "Johnson & Johnson",
    "LLY": "Eli Lilly and Company",
    "ABBV": "AbbVie Inc.",
    "MRK": "Merck & Co. Inc.",
    "TMO": "Thermo Fisher Scientific Inc.",
    "ABT": "Abbott Laboratories",
    "DHR": "Danaher Corporation",
    "BMY": "Bristol-Myers Squibb Company",
    "AMGN": "Amgen Inc.",
    "GILD": "Gilead Sciences Inc.",
    "VRTX": "Vertex Pharmaceuticals Incorporated",
    "ISRG": "Intuitive Surgical Inc.",
    "REGN": "Regeneron Pharmaceuticals Inc.",
    "BIIB": "Biogen Inc.",
    "IQV": "IQVIA Holdings Inc.",
    "ZTS": "Zoetis Inc.",
    "IDXX": "IDEXX Laboratories Inc.",
    "SYK": "Stryker Corporation",
    "BSX": "Boston Scientific Corporation",
    "EW": "Edwards Lifesciences Corporation",
    "BDX": "Becton Dickinson and Company",
    "MTD": "Mettler-Toledo International Inc.",
    "A": "Agilent Technologies Inc.",
    "HOLX": "Hologic Inc.",
    "ALGN": "Align Technology Inc.",
    "DXCM": "DexCom Inc.",
    "PODD": "Insulet Corporation",
    "HCA": "HCA Healthcare Inc.",
    "UHS": "Universal Health Services Inc.",
    "CNC": "Centene Corporation",
    "HUM": "Humana Inc.",
    "CI": "The Cigna Group",
    "ELV": "Elevance Health Inc.",
    "MOH": "Molina Healthcare Inc.",
    "MCK": "McKesson Corporation",
    "COR": "Cencora Inc.",
    "CAH": "Cardinal Health Inc.",
    "PFE": "Pfizer Inc.",
    "HSIC": "Henry Schein Inc.",
    "WAT": "Waters Corporation",
    "SOLV": "Solventum Corporation",
    "RVTY": "Revvity Inc.",
    "TECH": "Bio-Techne Corporation",
    "CRL": "Charles River Laboratories International Inc.",
    "ZBH": "Zimmer Biomet Holdings Inc.",
    "RMD": "ResMed Inc.",
    "GEHC": "GE HealthCare Technologies Inc.",
    "INCY": "Incyte Corporation",
    "BAX": "Baxter International Inc.",
    "DVA": "DaVita Inc.",
    "LH": "Labcorp Holdings Inc.",
    "DGX": "Quest Diagnostics Incorporated",
    "STE": "STERIS plc",
    "WST": "West Pharmaceutical Services Inc.",
    "TDY": "Teledyne Technologies Incorporated",
    "MRNA": "Moderna Inc.",
    "POOL": "Pool Corporation",
    # Financials
    "BRK-B": "Berkshire Hathaway Inc. (Class B)",
    "JPM": "JPMorgan Chase & Co.",
    "BAC": "Bank of America Corporation",
    "WFC": "Wells Fargo & Company",
    "GS": "The Goldman Sachs Group Inc.",
    "MS": "Morgan Stanley",
    "C": "Citigroup Inc.",
    "BLK": "BlackRock Inc.",
    "SPGI": "S&P Global Inc.",
    "MCO": "Moody's Corporation",
    "CB": "Chubb Limited",
    "AXP": "American Express Company",
    "V": "Visa Inc.",
    "MA": "Mastercard Incorporated",
    "PYPL": "PayPal Holdings Inc.",
    "ICE": "Intercontinental Exchange Inc.",
    "CME": "CME Group Inc.",
    "NDAQ": "Nasdaq Inc.",
    "CBOE": "Cboe Global Markets Inc.",
    "AON": "Aon plc",
    "MRSH": "Marsh & McLennan Companies Inc.",
    "AJG": "Arthur J. Gallagher & Co.",
    "WTW": "Willis Towers Watson Public Limited Company",
    "MET": "MetLife Inc.",
    "PRU": "Prudential Financial Inc.",
    "AFL": "Aflac Incorporated",
    "AIG": "American International Group Inc.",
    "HIG": "The Hartford Financial Services Group Inc.",
    "TRV": "The Travelers Companies Inc.",
    "PGR": "The Progressive Corporation",
    "ALL": "The Allstate Corporation",
    "L": "Loews Corporation",
    "ERIE": "Erie Indemnity Company",
    "USB": "U.S. Bancorp",
    "PNC": "The PNC Financial Services Group Inc.",
    "TFC": "Truist Financial Corporation",
    "KEY": "KeyCorp",
    "RF": "Regions Financial Corporation",
    "FITB": "Fifth Third Bancorp",
    "HBAN": "Huntington Bancshares Incorporated",
    "CFG": "Citizens Financial Group Inc.",
    "MTB": "M&T Bank Corporation",
    "SCHW": "The Charles Schwab Corporation",
    "RJF": "Raymond James Financial Inc.",
    "TROW": "T. Rowe Price Group Inc.",
    "STT": "State Street Corporation",
    "BK": "The Bank of New York Mellon Corporation",
    "NTRS": "Northern Trust Corporation",
    "FIS": "Fidelity National Information Services Inc.",
    "FISV": "Fiserv Inc.",
    "GPN": "Global Payments Inc.",
    "COF": "Capital One Financial Corporation",
    "SYF": "Synchrony Financial",
    "BX": "Blackstone Inc.",
    "KKR": "KKR & Co. Inc.",
    "APO": "Apollo Global Management Inc.",
    "ARES": "Ares Management Corporation",
    "BEN": "Franklin Resources Inc.",
    "IVZ": "Invesco Ltd.",
    "AMP": "Ameriprise Financial Inc.",
    "PFG": "Principal Financial Group Inc.",
    "ACGL": "Arch Capital Group Ltd.",
    "EG": "Everest Group Ltd.",
    "WRB": "W.R. Berkley Corporation",
    "CINF": "Cincinnati Financial Corporation",
    "AIZ": "Assurant Inc.",
    "COIN": "Coinbase Global Inc.",
    "HOOD": "Robinhood Markets Inc.",
    "IBKR": "Interactive Brokers Group Inc.",
    # Industrials
    "HON": "Honeywell International Inc.",
    "UNP": "Union Pacific Corporation",
    "RTX": "RTX Corporation",
    "CAT": "Caterpillar Inc.",
    "DE": "Deere & Company",
    "ETN": "Eaton Corporation plc",
    "NOC": "Northrop Grumman Corporation",
    "GD": "General Dynamics Corporation",
    "LMT": "Lockheed Martin Corporation",
    "LHX": "L3Harris Technologies Inc.",
    "TDG": "TransDigm Group Incorporated",
    "WM": "Waste Management Inc.",
    "RSG": "Republic Services Inc.",
    "CTAS": "Cintas Corporation",
    "ROP": "Roper Technologies Inc.",
    "GWW": "W.W. Grainger Inc.",
    "FAST": "Fastenal Company",
    "AME": "AMETEK Inc.",
    "VRSK": "Verisk Analytics Inc.",
    "EFX": "Equifax Inc.",
    "MSCI": "MSCI Inc.",
    "IT": "Gartner Inc.",
    "BR": "Broadridge Financial Solutions Inc.",
    "PAYC": "Paycom Software Inc.",
    "ITW": "Illinois Tool Works Inc.",
    "PH": "Parker-Hannifin Corporation",
    "ROK": "Rockwell Automation Inc.",
    "SWK": "Stanley Black & Decker Inc.",
    "XYL": "Xylem Inc.",
    "IR": "Ingersoll Rand Inc.",
    "CARR": "Carrier Global Corporation",
    "OTIS": "Otis Worldwide Corporation",
    "TT": "Trane Technologies plc",
    "JCI": "Johnson Controls International plc",
    "JBHT": "J.B. Hunt Transport Services Inc.",
    "CHRW": "C.H. Robinson Worldwide Inc.",
    "EXPD": "Expeditors International of Washington Inc.",
    "FDX": "FedEx Corporation",
    "UPS": "United Parcel Service Inc.",
    "ODFL": "Old Dominion Freight Line Inc.",
    "CSX": "CSX Corporation",
    "NSC": "Norfolk Southern Corporation",
    "WAB": "Westinghouse Air Brake Technologies Corporation",
    "DAL": "Delta Air Lines Inc.",
    "UAL": "United Airlines Holdings Inc.",
    "LUV": "Southwest Airlines Co.",
    "BA": "The Boeing Company",
    "PLTR": "Palantir Technologies Inc.",
    "AXON": "Axon Enterprise Inc.",
    "LDOS": "Leidos Holdings Inc.",
    "GE": "GE Aerospace",
    "GEV": "GE Vernova Inc.",
    "HWM": "Howmet Aerospace Inc.",
    "TXT": "Textron Inc.",
    "HII": "Huntington Ingalls Industries Inc.",
    "TKO": "TKO Group Holdings Inc.",
    "PWR": "Quanta Services Inc.",
    "FIX": "Comfort Systems USA Inc.",
    "EME": "EMCOR Group Inc.",
    "BLDR": "Builders FirstSource Inc.",
    "URI": "United Rentals Inc.",
    "TRMB": "Trimble Inc.",
    "NDSN": "Nordson Corporation",
    "DOV": "Dover Corporation",
    "SNA": "Snap-on Incorporated",
    "JKHY": "Jack Henry & Associates Inc.",
    "J": "Jacobs Solutions Inc.",
    "ADP": "Automatic Data Processing Inc.",
    "CPRT": "Copart Inc.",
    "GRMN": "Garmin Ltd.",
    "PCAR": "PACCAR Inc.",
    "CMI": "Cummins Inc.",
    "MMM": "3M Company",
    "EMR": "Emerson Electric Co.",
    "AOS": "A.O. Smith Corporation",
    "ALLE": "Allegion plc",
    "EPAM": "EPAM Systems Inc.",
    "GLW": "Corning Incorporated",
    "MSI": "Motorola Solutions Inc.",
    "APH": "Amphenol Corporation",
    "CRH": "CRH plc",
    "LULU": "lululemon athletica inc.",
    "TSN": "Tyson Foods Inc.",
    "VRSN": "VeriSign Inc.",
    # Energy
    "XOM": "Exxon Mobil Corporation",
    "CVX": "Chevron Corporation",
    "COP": "ConocoPhillips",
    "EOG": "EOG Resources Inc.",
    "SLB": "SLB N.V.",
    "MPC": "Marathon Petroleum Corporation",
    "PSX": "Phillips 66",
    "VLO": "Valero Energy Corporation",
    "HAL": "Halliburton Company",
    "DVN": "Devon Energy Corporation",
    "APA": "APA Corporation",
    "BKR": "Baker Hughes Company",
    "OKE": "ONEOK Inc.",
    "KMI": "Kinder Morgan Inc.",
    "WMB": "The Williams Companies Inc.",
    "EQT": "EQT Corporation",
    "CTRA": "Coterra Energy Inc.",
    "FANG": "Diamondback Energy Inc.",
    "OXY": "Occidental Petroleum Corporation",
    "NRG": "NRG Energy Inc.",
    "CEG": "Constellation Energy Corporation",
    "PCG": "PG&E Corporation",
    "EIX": "Edison International",
    "AES": "The AES Corporation",
    "TRGP": "Targa Resources Corp.",
    "EXE": "Expand Energy Corporation",
    "VST": "Vistra Corp.",
    # Materials
    "LIN": "Linde plc",
    "APD": "Air Products and Chemicals Inc.",
    "NUE": "Nucor Corporation",
    "FCX": "Freeport-McMoRan Inc.",
    "VMC": "Vulcan Materials Company",
    "MLM": "Martin Marietta Materials Inc.",
    "NEM": "Newmont Corporation",
    "BALL": "Ball Corporation",
    "CF": "CF Industries Holdings Inc.",
    "MOS": "The Mosaic Company",
    "CTVA": "Corteva Inc.",
    "DOW": "Dow Inc.",
    "LYB": "LyondellBasell Industries N.V.",
    "PPG": "PPG Industries Inc.",
    "SHW": "The Sherwin-Williams Company",
    "ECL": "Ecolab Inc.",
    "ALB": "Albemarle Corporation",
    "IFF": "International Flavors & Fragrances Inc.",
    "DD": "DuPont de Nemours Inc.",
    "STLD": "Steel Dynamics Inc.",
    "BG": "Bunge Global SA",
    "SW": "Smurfit Westrock plc",
    "IP": "International Paper Company",
    "PKG": "Packaging Corporation of America",
    "AMCR": "Amcor plc",
    # Real Estate
    "PLD": "Prologis Inc.",
    "AMT": "American Tower Corporation",
    "CCI": "Crown Castle Inc.",
    "EQIX": "Equinix Inc.",
    "PSA": "Public Storage",
    "DLR": "Digital Realty Trust Inc.",
    "O": "Realty Income Corporation",
    "SPG": "Simon Property Group Inc.",
    "WELL": "Welltower Inc.",
    "AVB": "AvalonBay Communities Inc.",
    "EQR": "Equity Residential",
    "VTR": "Ventas Inc.",
    "ESS": "Essex Property Trust Inc.",
    "UDR": "UDR Inc.",
    "CPT": "Camden Property Trust",
    "MAA": "Mid-America Apartment Communities Inc.",
    "REG": "Regency Centers Corporation",
    "KIM": "Kimco Realty Corporation",
    "FRT": "Federal Realty Investment Trust",
    "BXP": "BXP Inc.",
    "CBRE": "CBRE Group Inc.",
    "HST": "Host Hotels & Resorts Inc.",
    "ARE": "Alexandria Real Estate Equities Inc.",
    "VICI": "VICI Properties Inc.",
    "IRM": "Iron Mountain Incorporated",
    "EXR": "Extra Space Storage Inc.",
    "INVH": "Invitation Homes Inc.",
    "DOC": "Healthpeak Properties Inc.",
    "SBAC": "SBA Communications Corporation",
    # Utilities (and additional entries placed here alphabetically)
    "NEE": "NextEra Energy Inc.",
    "DUK": "Duke Energy Corporation",
    "SO": "The Southern Company",
    "D": "Dominion Energy Inc.",
    "EXC": "Exelon Corporation",
    "SRE": "Sempra",
    "AEP": "American Electric Power Company Inc.",
    "XEL": "Xcel Energy Inc.",
    "ED": "Consolidated Edison Inc.",
    "WEC": "WEC Energy Group Inc.",
    "DTE": "DTE Energy Company",
    "ES": "Eversource Energy",
    "ETR": "Entergy Corporation",
    "FE": "FirstEnergy Corp.",
    "NI": "NiSource Inc.",
    "CNP": "CenterPoint Energy Inc.",
    "CMS": "CMS Energy Corporation",
    "LNT": "Alliant Energy Corporation",
    "EVRG": "Evergy Inc.",
    "ATO": "Atmos Energy Corporation",
    "PNW": "Pinnacle West Capital Corporation",
    "AWK": "American Water Works Company Inc.",
    "PPL": "PPL Corporation",
    "AEE": "Ameren Corporation",
    # Additional confirmed S&P 500 members
    "Q": "Qnity Electronics Inc.",
    "SMCI": "Super Micro Computer Inc.",
    "VTRS": "Viatris Inc.",
    "VLTO": "Veralto Corporation",
    "SWKS": "Skyworks Solutions Inc.",
    "APTV": "Aptiv PLC",
    "ON": "ON Semiconductor Corporation",
    "FTV": "Fortive Corporation",
    "TYL": "Tyler Technologies Inc.",
    "TPL": "Texas Pacific Land Corporation",
    "FDS": "FactSet Research Systems Inc.",
    "FICO": "Fair Isaac Corporation",
    "PEG": "Public Service Enterprise Group Incorporated",
    "PNR": "Pentair plc",
    "HUBB": "Hubbell Incorporated",
    "ROL": "Rollins Inc.",
    "ZBRA": "Zebra Technologies Corporation",
    "CTSH": "Cognizant Technology Solutions Corporation",
    "ADM": "Archer-Daniels-Midland Company",
    "AVY": "Avery Dennison Corporation",
    "BRO": "Brown & Brown Inc.",
    "CDW": "CDW Corporation",
    "CIEN": "Ciena Corporation",
    "COO": "The Cooper Companies Inc.",
    "CSGP": "CoStar Group Inc.",
    "CPAY": "Corpay Inc.",
    "DPZ": "Domino's Pizza Inc.",
    "EXPE": "Expedia Group Inc.",
    "GEN": "Gen Digital Inc.",
    "GL": "Globe Life Inc.",
    "GNRC": "Generac Holdings Inc.",
    "IEX": "IDEX Corporation",
    "JBL": "Jabil Inc.",
    "KHC": "The Kraft Heinz Company",
    "LII": "Lennox International Inc.",
    "LW": "Lamb Weston Holdings Inc.",
    "MAS": "Masco Corporation",
    "MDT": "Medtronic plc",
    "MPWR": "Monolithic Power Systems Inc.",
    "PAYX": "Paychex Inc.",
    "PTC": "PTC Inc.",
    "TER": "Teradyne Inc.",
    "TEL": "TE Connectivity plc",
    "WY": "Weyerhaeuser Company",
    "WSM": "Williams-Sonoma Inc.",
}
